language: ruby

rvm:
  - 1.9.3
  - 2.1.0
  - jruby-19mode
  - rbx-2

env:
  - "RAILS_VERSION=3.2.18"
  - "RAILS_VERSION=4.0.6"
  - "RAILS_VERSION=4.1.2"

matrix:
  allow_failures:
    - rvm: jruby-19mode

script: bundle exec rake test
